### ISSUE TITLE
Generated taxonomy term models are not ordered based on the order in Kontent.ai

### ISSUE THREAD

**Issue by JiriLojda** [kontent-ai/model-generator-js#50]
### Brief bug description

Taxonomy terms in the `models/project/taxonomies.ts` are not always ordered as they are in Kontent.ai.

### Expected behavior

The taxonomy terms are ordered as they appear in the Kontent.ai app as the order is explicitly defined (e.g. for displaying them in the UI in the defined order).

**Comment by Enngage** [comment]
Currently, most items are ordered alphabetically based on their name/codename. I guess that for some scenarios it might be useful for them to be ordered the same way as they are in K.ai, but it seems a bit magical for someone to "know" this and depend on this (since most other items do not really have a specific order to them). 

I can introduce a configuration option to preserve the order for taxonomies, is it something we want to have?

**Comment by Enngage** [comment]
After internal discussion, we'll preserve the order items in which they appear in UI where possible.
